language: python
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirments.txt
script:
  - python manage.py test member
  - python manage.py test core
